name: Android APK Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Extra safety: force Gradle memory in CI
      GRADLE_OPTS: -Xmx4g -XX:MaxMetaspaceSize=1g

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

       # 3 initialize keystore
      - name: Set up keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/showa-release-key.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}


      # 3️⃣ Install JS dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Setup Java (required for Android)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # 5️⃣ Ensure gradlew is executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 6️⃣ Generate React Native JS bundle (CRITICAL)
      - name: Bundle React Native JS
        run: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

       
      # 7️⃣ Build Release APK
      - name: Build Release Bundle (AAB)
        run: |
          cd android
          ./gradlew clean
          ./gradlew bundleRelease --no-daemon

      # - name: Build Release APK
      #   run: |
      #     cd android
      #     ./gradlew clean
      #     ./gradlew assembleRelease --no-daemon
      

      # 8️⃣ Upload APK artifact
      - name: Upload Release Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab

      # - name: Upload APK
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release-apk
      #     path: android/app/build/outputs/apk/release/app-release.apk
